name: order_app
description: A new Restaurant application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:  ^0.5.8
  http: ^0.12.1
  fluttertoast: ^7.0.2
  flutter_spinkit: "^4.1.2"
  searchable_dropdown: ^1.1.3
  dropdownfield: ^1.0.3
  flutter_counter: ^1.0.3
  intl: ^0.16.1
  gradient_widgets: ^0.5.1
  flutter_launcher_icons: ^0.7.2+1
  badges: ^1.1.6
  firebase_messaging: ^7.0.3 
  geocoding: ^1.0.5
  shimmer: ^2.0.0
  geolocator: ^6.1.1
  flutter_test:
    sdk: flutter
  sqflite: ^1.3.0
  path_provider: ^1.6.27
  flutter_svg: ^0.19.2+1
flutter_icons:
  image_path: "assets/logo.jpg"
  android: true
  ios: true


flutter:
  assets:
    - assets/logo.png
    - assets/emptycart.png
    - assets/image.jpg
    - assets/burger.png
    - assets/idli.png
    - assets/icecream.png
    - assets/pizza.png
    - assets/dosa.png
    - assets/banner1.jpg
    - assets/curry.png
    - assets/fruits.png 
    - assets/user.png 
    - assets/User Icon.svg 
    - assets/Mail.svg 
    - assets/rupee.png 
    
    
    
  uses-material-design: true
